# Generated by Django 4.2.18 on 2025-01-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('learning_resources', models.TextField(help_text='Comma-separated list of links')),
                ('test_link', models.URLField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='englishlearn.language')),
            ],
        ),
    ]
